services:

  controller-api:
    image: $(edge-controller_TAG)
    #build:
    #  context: ./api
    #container_name: edge-controller-api
    restart: unless-stopped

    environment:
      DATABASE_URL: ${DATABASE_URL}

    ports:
      - "${API_PORT:-8080}:8080"

    depends_on:
      controller-postgres:
        condition: service_healthy

  controller-postgres:
    image: postgres:17

    container_name: edge-controller-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - controller-postgres-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:

  controller-postgres-data: